{{- if .Values.workers.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blamr.fullname" . }}-workers
  labels:
    {{- include "blamr.labels" . | nindent 4 }}
    app.kubernetes.io/component: workers
spec:
  replicas: {{ .Values.workers.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "blamr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: workers
  template:
    metadata:
      labels:
        {{- include "blamr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: workers
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "blamr.waitInitContainers" . | nindent 8 }}
      containers:
        - name: workers
          image: "{{ if .Values.global.imageRegistry }}{{ .Values.global.imageRegistry }}/{{ end }}{{ .Values.workers.image.repository }}:{{ .Values.workers.image.tag }}"
          imagePullPolicy: {{ .Values.workers.image.pullPolicy }}
          env:
            {{- include "blamr.workers.env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.workers.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
