{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blamr.fullname" . }}
  labels:
    {{- include "blamr.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
  ingest-secret: {{ required "secrets.ingestSecret is required" .Values.secrets.ingestSecret | quote }}
{{- end }}
